// Code generated by godddx, DO AVOID EDIT.
package sms

import (
	"database/sql/driver"
	"encoding/json"

	"github.com/ixugo/goddd/pkg/orm"
)

// MediaServerPorts domain model
type MediaServerPorts struct {
	HTTP     int `json:"http"`
	HTTPS    int `json:"https"`
	RTMP     int `json:"rtmp"`
	FLV      int `json:"flv"`
	FLVs     int `json:"flvs"`
	WsFLV    int `json:"ws_flv"`
	WsFLVs   int `json:"ws_flvs"`
	RTMPs    int `json:"rtmps"`
	RTPPorxy int `json:"rtpporxy"`
	RTSP     int `json:"rtsp"`
	RTSPs    int `json:"rtsps"`
}

// Scan implements orm.Scaner.
func (i *MediaServerPorts) Scan(input interface{}) error {
	return orm.JsonUnmarshal(input, i)
}

// Value implements driver.Valuer.
func (i MediaServerPorts) Value() (driver.Value, error) {
	return json.Marshal(i)
}
