// Code generated by gowebx, DO AVOID EDIT.
package proxydb

import (
	"github.com/gowvp/gb28181/internal/core/proxy"
	"gorm.io/gorm"
)

var _ proxy.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// StreamProxy Get business instance
func (d DB) StreamProxy() proxy.StreamProxyStorer {
	return StreamProxy(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(proxy.StreamProxy),
	); err != nil {
		panic(err)
	}
	return d
}
