// Code generated by gowebx, DO AVOID EDIT.
package uniqueid

import "github.com/ixugo/goweb/pkg/orm"

// UniqueID domain model
type UniqueID struct {
	ID        string   `gorm:"primaryKey" json:"id"`                                                               // 唯一 id
	CreatedAt orm.Time `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName database table name
func (*UniqueID) TableName() string {
	return "unique_ids"
}
