FROM debian:bullseye-slim

ENV TZ=Asia/Shanghai
WORKDIR /opt/media/bin/

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    tzdata \
    libstdc++6 \
    libgcc-s1 \
    libssl1.1 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=zlmediakit/zlmediakit:master /opt/media/bin /opt/media/bin

ADD ./build/linux_amd64/bin ./gowvp
ADD ./www ./www

RUN mkdir -p configs

LABEL Name=gowvp \
      Version=0.0.1 \
      Maintainer="xx@golang.space" \
      Description="gowvp & zlmediakit"

EXPOSE 15123 1935 8080 554 20000-20100/udp 20000-20100

CMD ["./gowvp"]
