FROM zlmediakit/zlmediakit:master

ENV TZ=Asia/Shanghai

WORKDIR /opt/media/bin/

# 添加应用程序文件
ADD ./build/linux_amd64/bin ./gowvp
ADD ./www ./www

# 创建配置目录
RUN mkdir -p configs

# 添加元数据标签
LABEL Name=gowvp \
      Version=0.0.1 \
      Maintainer="xx@golang.space" \
      Description="gowvp & zlmediakit"

# 暴露必要端口
EXPOSE 15123 1935 8080 554 10000-10500/udp

# 启动服务
CMD ["./gowvp"]