// Code generated by godddx, DO AVOID EDIT.
package gb28181db

import (
	"github.com/gowvp/gb28181/internal/core/gb28181"
	"gorm.io/gorm"
)

var _ gb28181.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// Device Get business instance
func (d DB) Device() gb28181.DeviceStorer {
	return Device(d)
}

// Channel Get business instance
func (d DB) Channel() gb28181.ChannelStorer {
	return Channel(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(gb28181.Device),
		new(gb28181.Channel),
	); err != nil {
		panic(err)
	}
	return d
}
