// Code generated by gowebx, DO AVOID EDIT.
package gb28181db

import (
	"context"

	"github.com/gowvp/gb28181/internal/core/gb28181"
	"github.com/ixugo/goweb/pkg/orm"
	"gorm.io/gorm"
)

var _ gb28181.DeviceStorer = Device{}

// Device Related business namespaces
type Device DB

// NewDevice instance object
func NewDevice(db *gorm.DB) Device {
	return Device{db: db}
}

// Find implements gb28181.DeviceStorer.
func (d Device) Find(ctx context.Context, bs *[]*gb28181.Device, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements gb28181.DeviceStorer.
func (d Device) Get(ctx context.Context, model *gb28181.Device, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Add implements gb28181.DeviceStorer.
func (d Device) Add(ctx context.Context, model *gb28181.Device) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Edit implements gb28181.DeviceStorer.
func (d Device) Edit(ctx context.Context, model *gb28181.Device, changeFn func(*gb28181.Device), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Del implements gb28181.DeviceStorer.
func (d Device) Del(ctx context.Context, model *gb28181.Device, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

func (d Device) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

func (d Device) EditWithSession(tx *gorm.DB, model *gb28181.Device, changeFn func(b *gb28181.Device) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
