// Code generated by godddx, DO AVOID EDIT.
package gb28181

import "github.com/ixugo/goddd/pkg/orm"

// Channel domain model
type Channel struct {
	ID        string    `gorm:"primaryKey" json:"id"`
	DID       string    `gorm:"column:did;index;notNull;default:'';comment:父级 ID" json:"did"`
	DeviceID  string    `gorm:"column:device_id;index;notNull;default:'';comment:国标编码" json:"device_id"`   // 国标编码
	ChannelID string    `gorm:"column:channel_id;index;notNull;default:'';comment:国标编码" json:"channel_id"` // 国标编码
	Name      string    `gorm:"column:name;notNull;default:'';comment:通道名称" json:"name"`                   // 通道名称
	PTZType   int       `gorm:"column:ptztype;notNull;default:0;comment:云台类型" json:"ptztype"`              // 云台类型
	IsOnline  bool      `gorm:"column:is_online;notNull;default:FALSE;comment:是否在线" json:"is_online"`      // 是否在线
	IsPlaying bool      `gorm:"column:is_playing;notNull;default:FALSE;comment:是否播放中" json:"is_playing"`   // 是否播放中
	Ext       DeviceExt `gorm:"column:ext;notNull;default:'{}';type:jsonb" json:"ext"`
	CreatedAt orm.Time  `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt orm.Time  `gorm:"column:updated_at;notNull;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName database table name
func (*Channel) TableName() string {
	return "channels"
}
