// Code generated by gowebx, DO AVOID EDIT.
package gb28181

import (
	"context"
	"log/slog"

	"github.com/ixugo/goweb/pkg/orm"
	"github.com/ixugo/goweb/pkg/web"
	"github.com/jinzhu/copier"
)

// ChannelStorer Instantiation interface
type ChannelStorer interface {
	Find(context.Context, *[]*Channel, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Channel, ...orm.QueryOption) error
	Add(context.Context, *Channel) error
	Edit(context.Context, *Channel, func(*Channel), ...orm.QueryOption) error
	Del(context.Context, *Channel, ...orm.QueryOption) error
}

// FindChannel Paginated search
func (c *Core) FindChannel(ctx context.Context, in *FindChannelInput) ([]*Channel, int64, error) {
	items := make([]*Channel, 0)
	total, err := c.store.Channel().Find(ctx, &items, in)
	if err != nil {
		return nil, 0, web.ErrDB.Withf(`Find err[%s]`, err.Error())
	}
	return items, total, nil
}

// GetChannel Query a single object
func (c *Core) GetChannel(ctx context.Context, id int) (*Channel, error) {
	var out Channel
	if err := c.store.Channel().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, web.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, web.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return &out, nil
}

// AddChannel Insert into database
func (c *Core) AddChannel(ctx context.Context, in *AddChannelInput) (*Channel, error) {
	var out Channel
	if err := copier.Copy(&out, in); err != nil {
		slog.Error("Copy", "err", err)
	}
	if err := c.store.Channel().Add(ctx, &out); err != nil {
		return nil, web.ErrDB.Withf(`Add err[%s]`, err.Error())
	}
	return &out, nil
}

// EditChannel Update object information
func (c *Core) EditChannel(ctx context.Context, in *EditChannelInput, id int) (*Channel, error) {
	var out Channel
	if err := c.store.Channel().Edit(ctx, &out, func(b *Channel) {
		if err := copier.Copy(b, in); err != nil {
			slog.Error("Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, web.ErrDB.Withf(`Edit err[%s]`, err.Error())
	}
	return &out, nil
}

// DelChannel Delete object
func (c *Core) DelChannel(ctx context.Context, id int) (*Channel, error) {
	var out Channel
	if err := c.store.Channel().Del(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, web.ErrDB.Withf(`Del err[%s]`, err.Error())
	}
	return &out, nil
}
