// Code generated by gowebx, DO AVOID EDIT.
package gb28181

import (
	"github.com/ixugo/goweb/pkg/web"
)

type FindDeviceInput struct {
	web.PagerFilter
	Key string `form:"key"`
	// DeviceID string `form:"device_id"` // 20 位国标编号
	// Name     string `form:"name"`      // 设备名称
	// ID       string `form:"id"`
	// Trasnport    string    `form:"trasnport"`   // 传输协议(TCP/UDP)
	// StreamMode   string    `form:"stream_mode"` // 数据传输模式(UDP/TCP_PASSIVE,TCP_ACTIVE)
	// IP           string    `form:"ip"`
	// Port         int       `form:"port"`
	// IsOnline     bool      `form:"is_online"`
	// RegisteredAt orm.Time  `form:"registered_at"` // 注册时间
	// KeepaliveAt  orm.Time  `form:"keepalive_at"`  // 心跳时间
	// Keepalives   int       `form:"keepalives"`    // 心跳间隔
	// Expires      int       `form:"expires"`       // 注册有效期
	// Channels     int       `form:"channels"`      // 通道数量
	// Ext          DeviceExt `form:"ext"`           // 设备属性
}

type EditDeviceInput struct {
	DeviceID   string `json:"device_id"`   // 20 位国标编号
	Name       string `json:"name"`        // 设备名称
	Password   string `json:"password"`    // 注册密码
	StreamMode int    `json:"stream_mode"` // 数据传输模式

	// IP           string    `json:"ip"`
	// Port         int       `json:"port"`
	// IsOnline     bool      `json:"is_online"`
	// RegisteredAt orm.Time  `json:"registered_at"` // 注册时间
	// KeepaliveAt  orm.Time  `json:"keepalive_at"`  // 心跳时间
	// Keepalives   int       `json:"keepalives"`    // 心跳间隔
	// Expires      int       `json:"expires"`       // 注册有效期
	// Channels     int       `json:"channels"`      // 通道数量
	// Ext          DeviceExt `json:"ext"`           // 设备属性
}

type AddDeviceInput struct {
	DeviceID string `json:"device_id"` // 20 位国标编号
	Name     string `json:"name"`      // 设备名称
	Password string `json:"password"`  // 注册密码

	// Trasnport    string    `json:"trasnport"`   // 传输协议(TCP/UDP)
	// StreamMode   string    `json:"stream_mode"` // 数据传输模式(UDP/TCP_PASSIVE,TCP_ACTIVE)
	// IP           string    `json:"ip"`
	// Port         int       `json:"port"`
	// IsOnline     bool      `json:"is_online"`
	// RegisteredAt orm.Time  `json:"registered_at"` // 注册时间
	// KeepaliveAt  orm.Time  `json:"keepalive_at"`  // 心跳时间
	// Keepalives   int       `json:"keepalives"`    // 心跳间隔
	// Expires      int       `json:"expires"`       // 注册有效期
	// Channels     int       `json:"channels"`      // 通道数量
	// Ext          DeviceExt `json:"ext"`           // 设备属性
}
