// Code generated by godddx, DO AVOID EDIT.
package gb28181

import (
	"database/sql/driver"
	"encoding/json"

	"github.com/ixugo/goddd/pkg/orm"
)

// DeviceExt domain model
type DeviceExt struct {
	Manufacturer string `json:"manufacturer"` // 生产厂商
	Model        string `json:"model"`        // 型号
	Firmware     string `json:"firmware"`     // 固件版本
	Name         string `json:"name"`         // 设备名
}

// Scan implements orm.Scaner.
func (i *DeviceExt) Scan(input interface{}) error {
	return orm.JsonUnmarshal(input, i)
}

func (i DeviceExt) Value() (driver.Value, error) {
	return json.Marshal(i)
}
