// Code generated by gowebx, DO AVOID EDIT.
package gb28181

import "github.com/ixugo/goweb/pkg/orm"

// DeviceExt domain model
type DeviceExt struct {
	Manufacturer string `json:"manufacturer"` // 生产厂商
	Model        string `json:"model"`        // 型号
	Firmware     string `json:"firmware"`     // 固件版本
}

// Scan implements orm.Scaner.
func (i *DeviceExt) Scan(input interface{}) error {
	return orm.JsonUnmarshal(input, i)
}
