// Code generated by gowebx, DO AVOID EDIT.
package mediadb

import (
	"github.com/gowvp/gb28181/internal/core/media"
	"gorm.io/gorm"
)

var _ media.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// StreamPush Get business instance
func (d DB) StreamPush() media.StreamPushStorer {
	return StreamPush(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(media.StreamPush),
	); err != nil {
		panic(err)
	}
	return d
}
