// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/gowvp/gb28181/internal/conf"
	"github.com/gowvp/gb28181/internal/data"
	"github.com/gowvp/gb28181/internal/web/api"
	"github.com/gowvp/gb28181/pkg/gbs"
	"github.com/ixugo/goddd/domain/version/versionapi"
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, log *slog.Logger) (http.Handler, func(), error) {
	db, err := data.SetupDB(bc, log)
	if err != nil {
		return nil, nil, err
	}
	core := versionapi.NewVersionCore(db)
	versionapiAPI := versionapi.New(core)
	smsCore := api.NewSMSCore(db, bc)
	smsAPI := api.NewSmsAPI(smsCore)
	uniqueidCore := api.NewUniqueID(db)
	pushCore := api.NewPushCore(db, uniqueidCore)
	storer := api.NewGB28181Store(db)
	gb28181 := api.NewGB28181(storer, uniqueidCore)
	server, cleanup := gbs.NewServer(bc, gb28181, smsCore)
	gb28181Core := api.NewGB28181Core(storer, uniqueidCore)
	webHookAPI := api.NewWebHookAPI(smsCore, pushCore, bc, server, gb28181Core)
	pushAPI := api.NewPushAPI(pushCore, smsCore, bc)
	gb28181API := api.NewGB28181API(gb28181Core)
	proxyAPI := api.NewProxyAPI(db, uniqueidCore)
	configAPI := api.NewConfigAPI(db, bc)
	userAPI := api.NewUserAPI(bc)
	usecase := &api.Usecase{
		Conf:       bc,
		DB:         db,
		Version:    versionapiAPI,
		SMSAPI:     smsAPI,
		WebHookAPI: webHookAPI,
		UniqueID:   uniqueidCore,
		MediaAPI:   pushAPI,
		GB28181API: gb28181API,
		ProxyAPI:   proxyAPI,
		ConfigAPI:  configAPI,
		SipServer:  server,
		UserAPI:    userAPI,
	}
	handler := api.NewHTTPHandler(usecase)
	return handler, func() {
		cleanup()
	}, nil
}
