// Code generated by godddx, DO AVOID EDIT.
package smsdb

import (
	"github.com/gowvp/gb28181/internal/core/sms"
	"gorm.io/gorm"
)

var _ sms.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// MediaServer Get business instance
func (d DB) MediaServer() sms.MediaServerStorer {
	return MediaServer(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(sms.MediaServer),
	); err != nil {
		panic(err)
	}
	return d
}
