// Code generated by gowebx, DO AVOID EDIT.
package smsdb

import (
	"context"

	"github.com/gowvp/gb28181/internal/core/sms"
	"github.com/ixugo/goweb/pkg/orm"
	"gorm.io/gorm"
)

var _ sms.MediaServerStorer = MediaServer{}

// MediaServer Related business namespaces
type MediaServer DB

// NewMediaServer instance object
func NewMediaServer(db *gorm.DB) MediaServer {
	return MediaServer{db: db}
}

// Find implements sms.MediaServerStorer.
func (d MediaServer) Find(ctx context.Context, bs *[]*sms.MediaServer, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements sms.MediaServerStorer.
func (d MediaServer) Get(ctx context.Context, model *sms.MediaServer, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Add implements sms.MediaServerStorer.
func (d MediaServer) Add(ctx context.Context, model *sms.MediaServer) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Edit implements sms.MediaServerStorer.
func (d MediaServer) Edit(ctx context.Context, model *sms.MediaServer, changeFn func(*sms.MediaServer), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Del implements sms.MediaServerStorer.
func (d MediaServer) Del(ctx context.Context, model *sms.MediaServer, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

func (d MediaServer) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

func (d MediaServer) EditWithSession(tx *gorm.DB, model *sms.MediaServer, changeFn func(b *sms.MediaServer) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
