// Code generated by gowebx, DO AVOID EDIT.
package media

// Storer data persistence
type Storer interface {
	StreamPush() StreamPushStorer
}

// Core business domain
type Core struct {
	store Storer
}

// NewCore create business domain
func NewCore(store Storer) *Core {
	return &Core{store: store}
}
