// Code generated by gowebx, DO AVOID EDIT.
package media

import "github.com/ixugo/goweb/pkg/orm"

// StreamPush domain model
type StreamPush struct {
	ID            int       `gorm:"primaryKey" json:"id"`
	App           string    `gorm:"column:app;notNull;default:'';comment:应用名" json:"app"`                               // 应用名
	CreatedAt     orm.Time  `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     orm.Time  `gorm:"column:updated_at;notNull;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	PushedAt      *orm.Time `gorm:"column:pushed_at;notNull;comment:最后一次推流时间" json:"pushed_at"`                         // 最后一次推流时间
	StoppedAt     *orm.Time `gorm:"column:stopped_at;notNull;comment:最后一次停止时间" json:"stopped_at"`                       // 最后一次停止时间
	Stream        string    `gorm:"column:stream;notNull;default:'';comment:流 ID" json:"stream"`                        // 流 ID
	MediaServerID string    `gorm:"column:media_server_id;notNull;default:'';comment:媒体服务器 ID" json:"media_server_id"`  // 媒体服务器 ID
	ServerID      string    `gorm:"column:server_id;notNull;default:'';comment:服务器 ID" json:"server_id"`                // 服务器 ID
	Status        string    `gorm:"column:status;notNull;default:'';comment:推流状态(PUSHING)" json:"status"`               // 推流状态(PUSHING)
}

// TableName database table name
func (*StreamPush) TableName() string {
	return "stream_pushs"
}
