// Code generated by gowebx, DO AVOID EDIT.
package media

import (
	"context"
	"log/slog"

	"github.com/ixugo/goweb/pkg/orm"
	"github.com/ixugo/goweb/pkg/web"
	"github.com/jinzhu/copier"
)

// StreamPushStorer Instantiation interface
type StreamPushStorer interface {
	Find(context.Context, *[]*StreamPush, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *StreamPush, ...orm.QueryOption) error
	Add(context.Context, *StreamPush) error
	Edit(context.Context, *StreamPush, func(*StreamPush), ...orm.QueryOption) error
	Del(context.Context, *StreamPush, ...orm.QueryOption) error
}

// FindStreamPush Paginated search
func (c *Core) FindStreamPush(ctx context.Context, in *FindStreamPushInput) ([]*StreamPush, int64, error) {
	items := make([]*StreamPush, 0)
	total, err := c.store.StreamPush().Find(ctx, &items, in)
	if err != nil {
		return nil, 0, web.ErrDB.Withf(`Find err[%s]`, err.Error())
	}
	return items, total, nil
}

// GetStreamPush Query a single object
func (c *Core) GetStreamPush(ctx context.Context, id int) (*StreamPush, error) {
	var out StreamPush
	if err := c.store.StreamPush().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, web.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, web.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return &out, nil
}

// AddStreamPush Insert into database
func (c *Core) AddStreamPush(ctx context.Context, in *AddStreamPushInput) (*StreamPush, error) {
	var out StreamPush
	if err := copier.Copy(&out, in); err != nil {
		slog.Error("Copy", "err", err)
	}
	if err := c.store.StreamPush().Add(ctx, &out); err != nil {
		return nil, web.ErrDB.Withf(`Add err[%s]`, err.Error())
	}
	return &out, nil
}

// EditStreamPush Update object information
func (c *Core) EditStreamPush(ctx context.Context, in *EditStreamPushInput, id int) (*StreamPush, error) {
	var out StreamPush
	if err := c.store.StreamPush().Edit(ctx, &out, func(b *StreamPush) {
		if err := copier.Copy(b, in); err != nil {
			slog.Error("Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, web.ErrDB.Withf(`Edit err[%s]`, err.Error())
	}
	return &out, nil
}

// DelStreamPush Delete object
func (c *Core) DelStreamPush(ctx context.Context, id int) (*StreamPush, error) {
	var out StreamPush
	if err := c.store.StreamPush().Del(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, web.ErrDB.Withf(`Del err[%s]`, err.Error())
	}
	return &out, nil
}
