// Code generated by gowebx, DO AVOID EDIT.
package media

import (
	"github.com/ixugo/goweb/pkg/orm"
	"github.com/ixugo/goweb/pkg/web"
)

type FindStreamPushInput struct {
	web.PagerFilter
	// App           string    `form:"app"`             // 应用名
	// PushedAt      *orm.Time `form:"pushed_at"`       // 最后一次推流时间
	// StoppedAt     *orm.Time `form:"stopped_at"`      // 最后一次停止时间
	// Stream        string    `form:"stream"`          // 流 ID
	// MediaServerID string    `form:"media_server_id"` // 媒体服务器 ID
	// ServerID      string    `form:"server_id"`       // 服务器 ID
	Status string `form:"status"` // 推流状态(PUSHING)
	Key    string `form:"key"`
}

type EditStreamPushInput struct {
	App    string `json:"app"`    // 应用名
	Stream string `json:"stream"` // 流 ID
	// MediaServerID string    `json:"media_server_id"` // 媒体服务器 ID
	// ServerID      string    `json:"server_id"`       // 服务器 ID
	// Status        string    `json:"status"`          // 推流状态(PUSHING)
}

type AddStreamPushInput struct {
	Name          string    `json:"name"`            // 推流名称
	App           string    `json:"app"`             // 应用名
	PushedAt      *orm.Time `json:"pushed_at"`       // 最后一次推流时间
	StoppedAt     *orm.Time `json:"stopped_at"`      // 最后一次停止时间
	Stream        string    `json:"stream"`          // 流 ID
	MediaServerID string    `json:"media_server_id"` // 媒体服务器 ID
	ServerID      string    `json:"server_id"`       // 服务器 ID
	Status        string    `json:"status"`          // 推流状态(PUSHING)
}

type FindStreamPushOutputItem struct {
	StreamPush
	PushAddrs []string `json:"push_addrs"`
}
