// Code generated by godddx, DO AVOID EDIT.
package proxy

import "github.com/ixugo/goddd/domain/uniqueid"

// Storer data persistence
type Storer interface {
	StreamProxy() StreamProxyStorer
}

// Core business domain
type Core struct {
	store    Storer
	uniqueID uniqueid.Core
}

// NewCore create business domain
func NewCore(store Storer, uni uniqueid.Core) *Core {
	return &Core{
		store:    store,
		uniqueID: uni,
	}
}
