// Code generated by gowebx, DO AVOID EDIT.
package proxy

import "github.com/ixugo/goweb/pkg/orm"

// StreamProxy domain model
type StreamProxy struct {
	ID                        string   `gorm:"primaryKey" json:"id"`
	CreatedAt                 orm.Time `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                              // 创建时间
	UpdatedAt                 orm.Time `gorm:"column:updated_at;notNull;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                              // 更新时间
	App                       string   `gorm:"column:app;uniqueIndex:idx_stream_proxys_app_stream;notNull;default:'';comment:应用名" json:"app"`                   // 应用名
	Stream                    string   `gorm:"column:stream;uniqueIndex:idx_stream_proxys_app_stream;notNull;default:'';comment:流 id" json:"stream"`            // 流 id
	MediaServerID             string   `gorm:"column:media_server_id;notNull;default:'';comment:媒体服务器 id" json:"media_server_id"`                               // 媒体服务器 id
	SourceURL                 string   `gorm:"column:source_url;notNull;default:'';comment:原始 url" json:"source_url"`                                           // 原始 url
	TimeoutS                  int      `gorm:"column:timeout_s;notNull;default:0;comment:超时时间(秒)" json:"timeout_s"`                                             // 超时时间(秒)
	Transport                 int      `gorm:"column:transport;notNull;default:0;comment:rtsp 拉流方式(0:udp;1:tcp)" json:"transport"`                              // rtsp 拉流方式(0:udp;1:tcp)
	Enabled                   bool     `gorm:"column:enabled;notNull;default:FALSE;comment:是否启用" json:"enabled"`                                                // 是否启用
	EnabledAudio              bool     `gorm:"column:enabled_audio;notNull;default:FALSE;comment:是否启用音频" json:"enabled_audio"`                                  // 是否启用音频
	EnabledRemoveNoneReader   bool     `gorm:"column:enabled_remove_none_reader;notNull;default:FALSE;comment:是否无人观看时删除" json:"enabled_remove_none_reader"`     // 是否无人观看时删除
	EnabledDisabledNoneReader bool     `gorm:"column:enabled_disabled_none_reader;notNull;default:FALSE;comment:是否无人观看时禁用" json:"enabled_disabled_none_reader"` // 是否无人观看时禁用
	StreamKey                 string   `gorm:"column:stream_key;notNull;default:'';comment:拉流代理时 zlm 返回的 key，用于停止拉流代理" json:"stream_key"`                       // 拉流代理时 zlm 返回的 key，用于停止拉流代理
	Pulling                   bool     `gorm:"column:pulling;notNull;default:FALSE;comment:拉流状态" json:"pulling"`                                                // 拉流状态
}

// TableName database table name
func (*StreamProxy) TableName() string {
	return "stream_proxys"
}
