// Code generated by godddx, DO AVOID EDIT.
package config

import "github.com/ixugo/goddd/pkg/web"

type FindConfigInput struct {
	web.PagerFilter
	Type string `form:"type"`
	Data Ext    `form:"data"`
}

type EditConfigInput struct {
	Type string `json:"type"`
	Data Ext    `json:"data"`
}

type AddConfigInput struct {
	Type string `json:"type"`
	Data Ext    `json:"data"`
}
