// Code generated by gowebx, DO AVOID EDIT.
package config

import "github.com/ixugo/goweb/pkg/orm"

// Ext domain model
type Ext struct {
	SIP *SIPConfig `json:"sip,omitempty"`
}

// Scan implements orm.Scaner.
func (i *Ext) Scan(input interface{}) error {
	return orm.JsonUnmarshal(input, i)
}

type SIPConfig struct {
	Host     string `json:"host"`
	Port     int    `json:"port"`
	ID       string `json:"id"`
	Domain   string `json:"domain"`
	Password string `json:"password"`
}
